### ISSUE TITLE
Build failure using Ninja generator

### ISSUE THREAD

**Issue by DanCraft99** [compnerd/swift-build-examples#1] opened 2019-06-16 13:04 UTC
With Xcode 10 and 10.2, this demo or any one line swift code will fail to build. Xcode generator works.

The error message:

ninja: Entering directory `out/'
[1/1] Linking Swift executable Test0
FAILED: Test0 CMakeFiles/Test0.dir/src/main.swift.o Test0.swiftmodule 
: && /usr/bin/swiftc -output-file-map CMakeFiles/Test0.dir/output-file-map.json -incremental -emit-executable -o Test0 -emit-module -emit-module-path Test0.swiftmodule -emit-dependencies    ../src/main.swift    && :
<unknown>:0: error: unable to load output file map 'CMakeFiles/Test0.dir/output-file-map.json': No such file or directory
ninja: build stopped: subcommand failed.

**Comment by DanCraft99** [comment] 2019-06-16 13:05
Need to add in

```
if(NOT XCODE_VERSION VERSION_LESS 10.2)
  set(CMAKE_Swift_LANGUAGE_VERSION 5.0)
elseif(NOT XCODE_VERSION VERSION_LESS 8.0)
  set(CMAKE_Swift_LANGUAGE_VERSION 3.0)
endif()
```
Ref: https://github.com/Kitware/CMake/blob/master/Tests/SwiftOnly/CMakeLists.txt

**Comment by compnerd** [comment] 2019-06-19 16:55
If you have to do that, it sounds like you are using the Xcode generator.  How did you configure the project?

**Comment by troughton** [comment] 2019-07-06 04:06
This issue seems to be caused by running `cmake` in a directory other than the build directory (and CMake placing files relative to the current rather than build directory). For example,

```
cd build
cmake -G Ninja ../ -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_TESTING=YES
```

works (although the tests still fail), but this doesn't:

```
cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_TESTING=YES
```

**Comment by compnerd** [comment] 2019-07-06 17:06
I wonder why the `-B` option doesn't work.  Does that work for other builds and not just swift?  If so, that might just be a bug in CMake that needs to be addressed.  But, yes, I believe that you are correct about it being run from the wrong directory.  I'm going to close this out.

**Closed as completed by compnerd** 2019-07-06 17:06 UTC
